/*globals define*/
function process(name,targetNamespace,xmlns,matter){
    var result = "<process name=\""+name+"\" targetNamespace=\""+targetNamespace+"\" xmlns=\""+xmlns+"\" >" + matter+ "</process>";
    return result;
}
function parterner_link(name,partnerLinkType,myRole,partnerRole){
    var result = "<partnerLink name=\"" + String(name)+"\" partnerLinkType=\""+partnerLinkType+"\" myRole=\""+myRole+"\" partnerRole=\""+partnerRole+"\"/>\n";
    return result;
}
function parterner_links(matter){
    var result = "<partnerLinks>\n"+matter +"\n</partnerLinks>";
    return result;
}
function variables(matter){
    var result = "<variables>\n"+matter +"\n</variables>";
    return result;
}
function variable(name,messageType){
    var result = "<variable name=\""+name+"\" messageType=\""+messageType+"\"/>";
    return result;
}
function sequence(matter){
    var result = "<sequence>"+matter+"</sequence>";
    return result;
}
function invoke(partnerLink,portType,operation,inputVariable,outputVariable){
    var result =  "<invoke partnerLink=\""+partnerLink+"\" portType=\""+portType+"\" operation=\""+operation+"\" inputVariable=\""+inputVariable+"\" outputVariable=\""+outputVariable+"\"/>";
    return result;
}
function recive(partnerLink,portType,operation,variable){
    var result = "<receive partnerLink=\""+partnerLink+"\" portType=\""+portType+"\" operation=\""+operation+"\" variable=\""+variable+"\" />";
    return result;
}
function assign(from ,to ){
    var result = "<assign><copy><from variable=\""+from +"\"/><to variable=\""+to+"\"/></copy></assign>";
    return result;
}
function _switch(matter){
    var result = "<switch>"+matter+"</switch>";
    return result;
}
function otherwise(matter){
    var result = "<otherwise>\n"+matter+"\n</otherwise>";
    return result;
}
function _case(condition,matter){
    var result = "<case condition=\""+condition+"\">\n" +matter+"\n</case>";
    return result;
}
/*eslint-env node, browser*/

/**
 * Generated by PluginGenerator 2.20.5 from webgme on Thu Apr 14 2022 13:45:22 GMT+0530 (India Standard Time).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase'
], function (
    PluginConfig,
    pluginMetadata,
    PluginBase) {
    'use strict';

    pluginMetadata = JSON.parse(pluginMetadata);

    /**
     * Initializes a new instance of final.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin final.
     * @constructor
     */
    function final() {
        // Call base class' constructor.
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    }

    /**
     * Metadata associated with the plugin. Contains id, name, version, description, icon, configStructure etc.
     * This is also available at the instance at this.pluginMetadata.
     * @type {object}
     */
    final.metadata = pluginMetadata;

    // Prototypical inheritance from PluginBase.
    final.prototype = Object.create(PluginBase.prototype);
    final.prototype.constructor = final;

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(Error|null, plugin.PluginResult)} callback - the result callback
     */
    final.prototype.main = function (callback) {
        // Use this to access core, project, result, logger etc from PluginBase.
        const self = this;

        // Using the logger.
        self.logger.debug('This is a debug message.');
        self.logger.info('This is an info message.');
        self.logger.warn('This is a warning message.');
        self.logger.error('This is an error message.');

        // Using the coreAPI to make changes.
        const nodeObject = self.activeNode;
        console.log(self.core.getAttribute(nodeObject,"name"));
        


        // This will save the changes. If you don't want to save;
        // exclude self.save and call callback directly from this scope.
        self.save('final updated model.')
            .then(() => {
                self.result.setSuccess(true);
                callback(null, self.result);
            })
            .catch((err) => {
                // Result success is false at invocation.
                self.logger.error(err.stack);
                callback(err, self.result);
            });
    };

    return final;
});
